name                        = "malik-app"
environment                 = "prod"
aws-region                  = "ap-souteast-2"
availability_zones          = ["ap-southeast-2a", "ap-southeast-2b", "ap-southeast-2c"]
# aws-region                  = "us-east-1"
# availability_zones          = ["us-east-1a", "us-east-1b", "us-east-1c"]
cidr                        = "10.10.0.0/16"
public_subnets              = ["10.10.11.0/24", "10.10.12.0/24", "10.10.13.0/24"]
private_subnets             = ["10.10.1.0/24", "10.10.2.0/24", "10.10.3.0/24"]
service_desired_count       = 2
postgresql_instance_class   = "db.t3.medium"
health_check_path           = "/healthcheck/"
container_port              = 3000
tag                         = "latest"
container_cpu               = 1024
container_memory            = 2048
db_name                     = "postgres"               
db_listen_host              = "0.0.0.0"
db_listen_port              = "3000"

# ecs_task_execution_role_name= "myEcsTaskExecutionRole"
# ecs_auto_scale_role_name    = "myEcsAutoScaleRole"
# certificate_arn             = ""
# container_count             = "2"
