name                        = "techChallengeServian"
environment                 = "prod"
aws-region                  = "ap-souteast-2"
availability_zones          = ["ap-southeast-2a", "ap-southeast-2b", "ap-southeast-2c"]
cidr                        = "10.10.0.0/16"
public_subnets              = ["10.10.11.0/24", "10.10.12.0/24", "10.10.13.0/24"]
private_subnets             = ["10.10.1.0/24", "10.10.2.0/24", "10.10.3.0/24"]
service_desired_count       = 3
container_port              = 3000
container_cpu               = 1024
container_memory            = 2048
# container_image             = "servian/techchallengeapp:latest"
tag                         = "latest"
health_check_path           = "/healthcheck/"
certificate_arn             = ""
# domain_name             = ""
# postgresql_version          = "10.11"
postgresql_instance_class   = "db.t3.medium"
ecs_task_execution_role_name= "myEcsTaskExecutionRole"
ecs_auto_scale_role_name    = "myEcsAutoScaleRole"
container_count             = "2"
